# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoF1 < Formula
  desc ""
  homepage "https://github.com/AidanFogarty/go-f1"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AidanFogarty/go-f1/releases/download/v1.1.0/go-f1_1.1.0_Darwin_arm64.tar.gz"
      sha256 "a54d3b3f748484ec30913fe00ef8fada63ceaf36f53b043bc657776615afb4d6"

      def install
        bin.install "go-f1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AidanFogarty/go-f1/releases/download/v1.1.0/go-f1_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "f5b89c83ff4487ccae7671c0824a9c8d732f6eed866c6dc8a3653f051eff0438"

      def install
        bin.install "go-f1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/AidanFogarty/go-f1/releases/download/v1.1.0/go-f1_1.1.0_Linux_x86_64.tar.gz"
      sha256 "4d8d0313d86d51e34c2b8ed9e708334ae8a2beb667331a9c2005374fd3c1261f"

      def install
        bin.install "go-f1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AidanFogarty/go-f1/releases/download/v1.1.0/go-f1_1.1.0_Linux_arm64.tar.gz"
      sha256 "545796104c4dc039160d846d1ed7b46dc292fa7f1b6fea831eae7c6ed163d1d3"

      def install
        bin.install "go-f1"
      end
    end
  end
end
