# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rgbx < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/AidanFogarty/rgbx/releases/download/v0.2.0/rgbx_Darwin_x86_64.tar.gz"
      sha256 "4d2f5aecd75971b490d652dd6809013f0553607875c3f39bdfb1b2e73909ae63"

      def install
        bin.install "rgbx"
      end
    end
    on_arm do
      url "https://github.com/AidanFogarty/rgbx/releases/download/v0.2.0/rgbx_Darwin_arm64.tar.gz"
      sha256 "b25a62efea47cae693bd8beff31033eac0521bbb8e3c94ba4a886e225ab5b259"

      def install
        bin.install "rgbx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AidanFogarty/rgbx/releases/download/v0.2.0/rgbx_Linux_x86_64.tar.gz"
        sha256 "3e6dedfd4582fa1041d8a844a51cb9fb3f9423cc93100b2646fdf19d58faa691"

        def install
          bin.install "rgbx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AidanFogarty/rgbx/releases/download/v0.2.0/rgbx_Linux_arm64.tar.gz"
        sha256 "7f4f3b8e41a3d1ae28ec748f910c77008ac5130abda4feab404cc930f2c2a507"

        def install
          bin.install "rgbx"
        end
      end
    end
  end
end
