# This file was generated by GoReleaser. DO NOT EDIT.
cask "pitwall" do
  name "pitwall"
  desc ""
  homepage ""
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pitwall"

  on_macos do
    on_intel do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Darwin_x86_64.tar.gz"
      sha256 "bc7b5c1ee31c2cbfef26166ae558d445331e5ebe237c7fb20e7060d7311e7820"
    end
    on_arm do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Darwin_arm64.tar.gz"
      sha256 "e4c7d5fd014dd72df286b6e928398cf81bcdc4e30b3a7a15952426f97c3e0a49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Linux_x86_64.tar.gz"
      sha256 "d2f99112daef6f54d7817a65ea10d79857e69ea6027ff8bd9212b9c88eb90d5b"
    end
    on_arm do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Linux_arm64.tar.gz"
      sha256 "19fa6a6826d02c411e517ae5a1710222cbbf0dd2275b076788d67f86297ac9e9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pitwall"]
    end
  end

  # No zap stanza required
end
