# This file was generated by GoReleaser. DO NOT EDIT.
cask "pitwall" do
  name "pitwall"
  desc ""
  homepage ""
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pitwall"

  on_macos do
    on_intel do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Darwin_x86_64.tar.gz"
      sha256 "ff79b73c81e3f0d6537f28860ace6135b5eb55664d5163fbb9a8b9d7b2803359"
    end
    on_arm do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Darwin_arm64.tar.gz"
      sha256 "2850e6532d3b030d1b52d5230cd168f4e22ed8aa5750a9d21b909b2a8dff31e5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Linux_x86_64.tar.gz"
      sha256 "4bbf654b8e5cec51a2a52c26e67515dd5a1f43a2ad389052ce2f686fc573a2d4"
    end
    on_arm do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Linux_arm64.tar.gz"
      sha256 "3ad540b60ddb34a0a3b3f3f16fc1d6720f6b3f18ab5688990c961c3720a44dbd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pitwall"]
    end
  end

  # No zap stanza required
end
