# This file was generated by GoReleaser. DO NOT EDIT.
cask "pitwall" do
  name "pitwall"
  desc ""
  homepage ""
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pitwall"

  on_macos do
    on_intel do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Darwin_x86_64.tar.gz"
      sha256 "a504ecd3bc17424040029d75db42efad4ec856d355a55cd87b939c6d4b20bfce"
    end
    on_arm do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Darwin_arm64.tar.gz"
      sha256 "7002218a93b7df882a6df681e7f597cc8e52ab165befcad8b7b0e81d1ecf10ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Linux_x86_64.tar.gz"
      sha256 "b4f42735f397c76a24a31f407cefc996b2277424495fce5d287fcee7e043c2f4"
    end
    on_arm do
      url "https://github.com/AidanFogarty/pitwall/releases/download/v#{version}/pitwall_Linux_arm64.tar.gz"
      sha256 "b08da79b48f6629299e4918acca7424e69108cae572b5f398c991488b7aa2330"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pitwall"]
    end
  end

  # No zap stanza required
end
